config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  resources :teachers, only: [:update, :show, :index]

  root to: 'welcome#index'
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    teachers_path
  end
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!

  def edit
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def index
    @teachers = Teacher.all
  end

  def update
     if current_teacher.update_attributes(teacher_params)
       flash[:notice] = "User information updated"
       redirect_to teacher_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_teacher_registration_path
     end
   end
 
   private
 
   def teacher_params
     params.require(:teacher).permit(:name, :theme, :bio, :schedule, :avatar)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Yoke</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <%= link_to "The Yoke", root_path %>
        <div class="pull-right user-info">
           <% if current_teacher %>
             Hello <%= link_to current_teacher.name, edit_teacher_registration_path %>! <%= link_to "Sign out", destroy_teacher_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_teacher_session_path %> or
             <%= link_to "Sign Up", new_teacher_registration_path %>
           <% end %>
         </div>
    </ul>

    <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

  <%= yield %>
  </div>


</html>

app/views/teachers/edit.html.erb
<h1>Edit Information</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines:</p>
     <ul>
       <li>We recommend first and last name.</li>
       <li>Remember, your unique URL is <b>pagetitle.theyoke.com</b></li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @teacher do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter name" %>
       </div>
       <div class="form-group">
         <%= f.label :theme %>
         <%= f.text_field :theme, class: 'form-control', placeholder: "Choose theme" %>
       </div>
       <div class="form-group">
         <%= f.label :bio %>
         <%= f.text_field :bio, rows: 8, class: 'form-control', placeholder: "Write a short bio" %>
       </div>
       <div class="form-group">
         <%= f.label :schedule %>
         <%= f.text_field :schedule, rows: 8, class: 'form-control', placeholder: "Enter your schedule" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/teachers/index.html.erb
<h1>All Teachers</h1>
<% @teachers.each do |teacher| %>
  <p><%= link_to teacher.name, teacher %></p>
<% end %>

app/views/teachers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
    
      <div class="jumbotron">
      <div class="panel-body">
          <div class="row">
          <small>
             <%= image_tag(teacher.avatar.tiny.url) if teacher.avatar? %>
           </small>
                  <h2><%= @teacher.name %> </h2>
                      <p><strong>About: </strong> <%= @teacher.bio %></p>
                      <p><strong>Schedule: </strong> <%= @teacher.schedule %></p>
              </div>          
          </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1><i>Hi.  Welcome to The Yoke.</i></h1>
  <p>Build your own personal yoga webpage in less than 10 minutes.</p>
  <p>
  <div class ="text-center">
      <%= link_to "Create your page!", new_teacher_registration_path, class: 'btn btn-success' %>
  </div>
  </p>
</div>